resources:
  - name: myGitRepo
    type: GitRepo
    configuration:
      gitProvider: my_github
      path: sangangu/maven-project
      branches:
        include: master
  - name: myBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: My_Own
      buildName: SampleApp
      buildNumber: 1          
pipelines:  
  - name: maven_pipeline
    steps:
      - shell:
        script: "echo Build Number: $BUILD_NUMBER"
      - maven:
      goals: clean install
        pom-file: "pom.xml"
    after:
      - artifacts:
        include: "employees-app/target/*"
    settings:
      - discard-old:
        days-to-keep-build: 5
        builds-to-keep: 10
        days-to-keep-artifacts: 5
        artifacts-to-keep: 10
