resources:
  - name: myGitRepo
    type: GitRepo
    configuration:
      gitProvider: my_github
      path: sangangu/maven-project
      branches:
        include: master
  - name: myBuildInfos
    type: BuildInfo
    configuration:
      sourceArtifactory: My_Own
      buildName: SampleApp
      buildNumber: 1          
pipelines:
  - name: demo_application
    configuration:
      environmentVariables:
        readOnly:
          JFROG_CLI_BUILD_NAME: backend_build
    steps:
      - name: bld_backend
        type: MvnBuild
        configuration:
          sourceLocation: .
          mvnCommand: clean install -ntp
          configFileLocation: .
          configFileName: mvn-art-config
          inputResources:
            - name: myGitRepo
          integrations:
            - name: My_Own 
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - "11"
        execution:
          onStart:
            - javac -version
            - mvn --version

